-- Create the congratulations table
create table if not exists congratulations (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies (optional, for public read/write)
alter table congratulations enable row level security;

create policy "Anyone can insert congratulations"
  on congratulations for insert
  with check (true);

create policy "Anyone can read congratulations"
  on congratulations for select
  using (true);